version: '3'

services:
  redis-cluster:
    container_name: redis_cluster
    image: grokzen/redis-cluster:latest
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=6379
      - MASTERS=3
      - SLAVES_PER_MASTER=1
    ports:
      - 6379-6384:6379-6384
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672