server:
  port: 8085

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create-drop

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb

  h2:
    console:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #TODO:: not working find out why
    dynamic: true

  profiles:
    include: oauth

#  session:
#    store-type: jdbc


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  host: 127.0.0.1
  port: 6666

queue:
  fname: q.test
  sname: q.test-sec