server:
  port: 8085

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
      username: local_rdb_master
      password: local_rdb

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #TODO:: not working find out why
    dynamic: true

  profiles:
    include: oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  host: 127.0.0.1
  port: 6666

queue:
  fname: q.test
  sname: q.test-sec