server:
  port: 8085

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb

  h2:
    console:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    include: oauth

  session:
    store-type: jdbc

test:
  host: 127.0.0.1
  port: 6666

queue:
  name: test